#!/bin/bash

listcontents -e COPYING .vite/deps config/grafana.json config/logging.conf config/nginx.conf.d/default.conf config/nginx.conf.d/shashguru.conf config/redis.conf docker-compose-ai-pc.yml docker-compose-ov.yml docker-compose-vllm-mate.yml docker-compose-vllm.yml frontend/.env frontend/vite.config.js frontend/package-lock.json frontend/public/favicon.ico
