#!/bin/bash

listcontents -e COPYING .vite/deps config/grafana.json config/logging.conf config/nginx.conf.d/default.conf config/nginx.conf.d/shashguru.conf config/redis.conf docker-compose.dev.yml docker-compose.prod.yml docker-compose.yml frontend/.env frontend/vite.config.js frontend/package-lock.json frontend/public/favicon.ico
